# Generated by Django 2.0.3 on 2018-04-01 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursomoodle',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tiempodedicadoestudiantecursomoodle',
            unique_together={('curso', 'timestamp', 'tipo', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='tiempodedicadocursomoodle',
            unique_together={('curso', 'timestamp', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='materialcursomoodle',
            unique_together={('curso', 'nombre', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='cursomoodle',
            unique_together={('profesor', 'nombre')},
        ),
    ]
