# Generated by Django 2.0 on 2018-01-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='token',
        ),
    ]
